### ISSUE TITLE
Serial debug

### ISSUE THREAD

**Issue by user-hash** [wtremmel/MQTTClient#2]
I have problems accesing serial debug information. I uncommented the line after serial.begin, but still no debug entries. I connected the led and it shows yellow light, but its not connected to wifi. Any ideas? 
I compiled the code normally and uploaded data folder too.
Thanks!

**Comment by wtremmel** [comment]
I did a complete rewrite at https://github.com/wtremmel/esp8266-mqtt-sensor-client - please check this
